import Antigravity from "@lobehub/icons/es/Antigravity";
import Codex from "@lobehub/icons/es/Codex";
import type { IconType as LobeIconType } from "@lobehub/icons/es/types";
import type { ComponentType } from "react";
import type { IconType } from "react-icons";
import { FaAws, FaInfinity, FaWindows } from "react-icons/fa";
import { PiMicrosoftOutlookLogoFill } from "react-icons/pi";
import {
  SiAndroidstudio,
  SiDart,
  SiDjango,
  SiDocker,
  SiFlutter,
  SiGit,
  SiGithubcopilot,
  SiGrafana,
  SiHubspot,
  SiIos,
  SiJavascript,
  SiKotlin,
  SiLetsencrypt,
  SiLinux,
  SiMikrotik,
  SiMinio,
  SiNodedotjs,
  SiNotion,
  SiPostgresql,
  SiProxmox,
  SiPython,
  SiReact,
  SiShopify,
  SiSupabase,
  SiSwagger,
  SiSwift,
  SiSynology,
  SiStripe,
  SiTailwindcss,
  SiTailscale,
  SiTelegram,
  SiTypescript,
  SiVercel,
  SiWhatsapp,
  SiWordpress,
  SiXcode,
  SiZapier,
} from "react-icons/si";
import { ZohoLogo } from "@/components/home/tech-stack/logos/ZohoLogo";

export type TechStackCategory =
  | "Development & Code"
  | "Data & Backend"
  | "Cloud, Infrastructure & DevOps"
  | "Mobile & Apps"
  | "Business, Automation & Commerce"
  | "Design & Creative";

export type TechStackItem = {
  id: string;
  name: string;
  category: TechStackCategory;
  icon?: IconType;
  lobeIcon?: LobeIconType;
  customIcon?: ComponentType<{ className?: string }>;
  imageSrc?: string;
  imageClassName?: string;
  iconClassName?: string;
  lobeIconSize?: number;
  color?: string;
  alt?: string;
  fallback?: string;
};

export const techStackItems: TechStackItem[] = [
  {
    id: "vscode",
    name: "VS Code",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/vscode.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "antigravity",
    name: "Antigravity",
    category: "Development & Code",
    lobeIcon: Antigravity.Color,
    lobeIconSize: 34,
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    category: "Development & Code",
    icon: SiGithubcopilot,
    color: "#FFFFFF",
  },
  {
    id: "codex",
    name: "Codex",
    category: "Development & Code",
    lobeIcon: Codex.Color,
    lobeIconSize: 34,
  },
  {
    id: "coderabbit",
    name: "CodeRabbit",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/coderabbit.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "kiro",
    name: "Kiro.dev",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/kiro.svg",
    imageClassName: "h-8 w-8 rounded-[12px] object-contain lg:h-9 lg:w-9",
  },
  {
    id: "claude-code",
    name: "Claude Code",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/claude-code.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "github",
    name: "GitHub",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/github.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "git",
    name: "Git",
    category: "Development & Code",
    icon: SiGit,
    color: "#F05032",
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/gitlab.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "javascript",
    name: "JavaScript",
    category: "Development & Code",
    icon: SiJavascript,
    color: "#F7DF1E",
  },
  {
    id: "html",
    name: "HTML",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/html.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "typescript",
    name: "TypeScript",
    category: "Development & Code",
    icon: SiTypescript,
    color: "#3178C6",
  },
  {
    id: "python",
    name: "Python",
    category: "Development & Code",
    icon: SiPython,
    color: "#3776AB",
  },
  {
    id: "django",
    name: "Django",
    category: "Development & Code",
    icon: SiDjango,
    color: "#44B78B",
  },
  {
    id: "react",
    name: "React",
    category: "Development & Code",
    icon: SiReact,
    color: "#61DAFB",
  },
  {
    id: "nextjs",
    name: "Next.js",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/nextjs.svg",
    imageClassName: "h-9 w-9 rounded-full object-contain lg:h-10 lg:w-10",
  },
  {
    id: "angular",
    name: "Angular",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/angular.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "bootstrap",
    name: "Bootstrap",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/bootstrap.svg",
    imageClassName: "h-8 w-9 object-contain lg:h-9 lg:w-10",
  },
  {
    id: "nodejs",
    name: "Node.js",
    category: "Development & Code",
    icon: SiNodedotjs,
    color: "#5FA04E",
  },
  {
    id: "v0",
    name: "v0",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/v0.svg",
    imageClassName: "h-7 w-9 object-contain lg:h-8 lg:w-10",
  },
  {
    id: "playwright",
    name: "Playwright",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/playwright.svg",
    imageClassName: "h-9 w-9 object-contain lg:h-10 lg:w-10",
  },
  {
    id: "postman",
    name: "Postman",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/postman.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "tailwindcss",
    name: "Tailwind CSS",
    category: "Development & Code",
    icon: SiTailwindcss,
    color: "#38BDF8",
  },
  {
    id: "dotenvx",
    name: ".ENV",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/dotenvx.svg",
    imageClassName: "h-8 w-8 rounded-[8px] object-contain lg:h-9 lg:w-9",
  },
  {
    id: "gradle",
    name: "Gradle",
    category: "Development & Code",
    imageSrc: "/assets/tech-stack/gradle.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "mysql",
    name: "MySQL",
    category: "Data & Backend",
    imageSrc: "/assets/tech-stack/mysql.svg",
    imageClassName: "h-7 w-12 object-contain lg:h-8 lg:w-14",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    category: "Data & Backend",
    icon: SiPostgresql,
    color: "#4169E1",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "Data & Backend",
    icon: SiSupabase,
    color: "#3FCF8E",
  },
  {
    id: "minio",
    name: "MinIO",
    category: "Data & Backend",
    icon: SiMinio,
    color: "#C72E49",
  },
  {
    id: "mariadb",
    name: "MariaDB",
    category: "Data & Backend",
    imageSrc: "/assets/tech-stack/mariadb.svg",
    imageClassName: "h-7 w-12 object-contain lg:h-8 lg:w-14",
  },
  {
    id: "redis",
    name: "Redis",
    category: "Data & Backend",
    imageSrc: "/assets/tech-stack/redis.svg",
    imageClassName: "h-7 w-12 object-contain lg:h-8 lg:w-14",
  },
  {
    id: "swagger",
    name: "Swagger",
    category: "Data & Backend",
    icon: SiSwagger,
    color: "#85EA2D",
  },
  {
    id: "openapi",
    name: "OpenAPI",
    category: "Data & Backend",
    imageSrc: "/assets/tech-stack/openapi.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "aws",
    name: "AWS",
    category: "Cloud, Infrastructure & DevOps",
    icon: FaAws,
    color: "#FF9900",
  },
  {
    id: "google-cloud",
    name: "Google Cloud",
    category: "Cloud, Infrastructure & DevOps",
    imageSrc: "/assets/tech-stack/google-cloud-2026.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "Cloud, Infrastructure & DevOps",
    imageSrc: "/assets/tech-stack/cloudflare.svg",
    imageClassName: "h-7 w-12 object-contain lg:h-8 lg:w-14",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "Cloud, Infrastructure & DevOps",
    icon: SiVercel,
    color: "#FFFFFF",
  },
  {
    id: "docker",
    name: "Docker",
    category: "Cloud, Infrastructure & DevOps",
    icon: SiDocker,
    color: "#2496ED",
  },
  {
    id: "nginx",
    name: "Nginx",
    category: "Cloud, Infrastructure & DevOps",
    imageSrc: "/assets/tech-stack/nginx.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "nginx-proxy-manager",
    name: "Nginx Proxy Manager",
    category: "Cloud, Infrastructure & DevOps",
    imageSrc: "/assets/tech-stack/nginx-proxy-manager.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "tailscale",
    name: "Tailscale",
    category: "Cloud, Infrastructure & DevOps",
    icon: SiTailscale,
    color: "#FFFFFF",
  },
  {
    id: "linux",
    name: "Linux",
    category: "Cloud, Infrastructure & DevOps",
    icon: SiLinux,
    color: "#FCC624",
  },
  {
    id: "devops",
    name: "DevOps",
    category: "Cloud, Infrastructure & DevOps",
    icon: FaInfinity,
    color: "#F97316",
  },
  {
    id: "contabo",
    name: "Contabo",
    category: "Cloud, Infrastructure & DevOps",
    imageSrc: "/assets/tech-stack/contabo.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    category: "Cloud, Infrastructure & DevOps",
    imageSrc: "/assets/tech-stack/digitalocean.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "hostinger",
    name: "Hostinger",
    category: "Cloud, Infrastructure & DevOps",
    imageSrc: "/assets/tech-stack/hostinger.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "namecheap",
    name: "Namecheap",
    category: "Cloud, Infrastructure & DevOps",
    imageSrc: "/assets/tech-stack/namecheap.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "godaddy",
    name: "GoDaddy",
    category: "Cloud, Infrastructure & DevOps",
    imageSrc: "/assets/tech-stack/godaddy.png",
    imageClassName: "h-8 w-[3.25rem] object-contain lg:h-9 lg:w-[3.75rem]",
  },
  {
    id: "cloudinary",
    name: "Cloudinary",
    category: "Cloud, Infrastructure & DevOps",
    imageSrc: "/assets/tech-stack/cloudinary.svg",
    imageClassName: "h-7 w-12 object-contain lg:h-8 lg:w-14",
  },
  {
    id: "prometheus",
    name: "Prometheus",
    category: "Cloud, Infrastructure & DevOps",
    imageSrc: "/assets/tech-stack/prometheus.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "synology",
    name: "Synology",
    category: "Cloud, Infrastructure & DevOps",
    icon: SiSynology,
    color: "#B5B5B6",
  },
  {
    id: "mikrotik",
    name: "MikroTik",
    category: "Cloud, Infrastructure & DevOps",
    icon: SiMikrotik,
    color: "#FFFFFF",
  },
  {
    id: "letsencrypt",
    name: "Let’s Encrypt",
    category: "Cloud, Infrastructure & DevOps",
    icon: SiLetsencrypt,
    color: "#2C7FB8",
  },
  {
    id: "grafana",
    name: "Grafana",
    category: "Cloud, Infrastructure & DevOps",
    icon: SiGrafana,
    color: "#F46800",
  },
  {
    id: "proxmox-ve",
    name: "Proxmox VE",
    category: "Cloud, Infrastructure & DevOps",
    icon: SiProxmox,
    color: "#E57000",
  },
  {
    id: "flutter",
    name: "Flutter",
    category: "Mobile & Apps",
    icon: SiFlutter,
    color: "#45D1FD",
  },
  {
    id: "capacitor",
    name: "Capacitor",
    category: "Mobile & Apps",
    imageSrc: "/assets/tech-stack/capacitor.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "dart",
    name: "Dart",
    category: "Mobile & Apps",
    icon: SiDart,
    color: "#0175C2",
  },
  {
    id: "android-studio",
    name: "Android Studio",
    category: "Mobile & Apps",
    icon: SiAndroidstudio,
    color: "#3DDC84",
  },
  {
    id: "kotlin",
    name: "Kotlin",
    category: "Mobile & Apps",
    icon: SiKotlin,
    color: "#A97BFF",
  },
  {
    id: "xcode",
    name: "Xcode",
    category: "Mobile & Apps",
    icon: SiXcode,
    color: "#147EFB",
  },
  {
    id: "swift",
    name: "Swift",
    category: "Mobile & Apps",
    icon: SiSwift,
    color: "#F05138",
  },
  {
    id: "firebase",
    name: "Firebase",
    category: "Mobile & Apps",
    imageSrc: "/assets/tech-stack/firebase.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "firebase-studio",
    name: "Firebase Studio",
    category: "Mobile & Apps",
    imageSrc: "/assets/tech-stack/firebase-studio.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "ios",
    name: "iOS",
    category: "Mobile & Apps",
    icon: SiIos,
    color: "#FFFFFF",
  },
  {
    id: "wordpress",
    name: "WordPress",
    category: "Business, Automation & Commerce",
    icon: SiWordpress,
    color: "#21759B",
  },
  {
    id: "shopify",
    name: "Shopify",
    category: "Business, Automation & Commerce",
    icon: SiShopify,
    color: "#95BF47",
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/woocommerce.svg",
    imageClassName: "h-8 w-12 object-contain lg:h-9 lg:w-14",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "Business, Automation & Commerce",
    icon: SiStripe,
    color: "#635BFF",
  },
  {
    id: "paypal",
    name: "PayPal",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/paypal.svg",
    imageClassName: "h-9 w-9 object-contain lg:h-10 lg:w-10",
  },
  {
    id: "apple-pay",
    name: "Apple Pay",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/apple-pay.svg",
    imageClassName: "h-7 w-10 object-contain lg:h-8 lg:w-12",
  },
  {
    id: "google-pay",
    name: "Google Pay",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/google-pay.svg",
    imageClassName: "h-7 w-[3.25rem] object-contain lg:h-8 lg:w-[3.75rem]",
  },
  {
    id: "paymob",
    name: "Paymob",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/paymob.png",
    imageClassName: "h-7 w-10 object-contain lg:h-8 lg:w-12",
  },
  {
    id: "tabby",
    name: "Tabby",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/tabby.png",
    imageClassName: "h-9 w-9 rounded-[12px] object-contain lg:h-10 lg:w-10",
  },
  {
    id: "zapier",
    name: "Zapier",
    category: "Business, Automation & Commerce",
    icon: SiZapier,
    color: "#FF4F00",
  },
  {
    id: "n8n",
    name: "n8n",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/n8n.svg",
    imageClassName: "h-7 w-12 object-contain lg:h-8 lg:w-14",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    category: "Business, Automation & Commerce",
    icon: SiHubspot,
    color: "#FF7A59",
  },
  {
    id: "zoho",
    name: "Zoho",
    category: "Business, Automation & Commerce",
    customIcon: ZohoLogo,
    iconClassName: "h-8 w-14 lg:h-9 lg:w-16",
  },
  {
    id: "google",
    name: "Google",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/google-g.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "google-business-profile",
    name: "Google Business Profile",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/google-business-profile.svg",
    imageClassName: "h-8 w-9 object-contain lg:h-9 lg:w-10",
  },
  {
    id: "google-drive",
    name: "Google Drive",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/google-drive.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "gmail",
    name: "Gmail",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/gmail.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "outlook",
    name: "Outlook",
    category: "Business, Automation & Commerce",
    icon: PiMicrosoftOutlookLogoFill,
    color: "#0078D4",
  },
  {
    id: "zoom",
    name: "Zoom",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/zoom.svg",
    imageClassName: "h-9 w-9 object-contain lg:h-10 lg:w-10",
  },
  {
    id: "telegram",
    name: "Telegram",
    category: "Business, Automation & Commerce",
    icon: SiTelegram,
    color: "#26A5E4",
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    category: "Business, Automation & Commerce",
    icon: SiWhatsapp,
    color: "#25D366",
  },
  {
    id: "meta",
    name: "Meta",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/meta.svg",
    imageClassName: "h-7 w-10 object-contain lg:h-8 lg:w-12",
  },
  {
    id: "microsoft",
    name: "Microsoft",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/microsoft.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "microsoft-365",
    name: "Microsoft 365",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/microsoft-365.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "clerk",
    name: "Clerk",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/clerk.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "home-assistant",
    name: "Home Assistant",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/home-assistant.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "smartthings",
    name: "SmartThings",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/smartthings.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "chrome",
    name: "Google Chrome",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/chrome.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "plex",
    name: "Plex Media Server",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/plex.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "slack",
    name: "Slack",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/slack.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "windows",
    name: "Windows",
    category: "Business, Automation & Commerce",
    icon: FaWindows,
    color: "#00A4EF",
  },
  {
    id: "anydesk",
    name: "AnyDesk",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/anydesk.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "adguard",
    name: "AdGuard",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/adguard.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "testsprite",
    name: "TestSprite",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/testsprite.png",
    imageClassName: "h-8 w-8 rounded-[10px] object-contain lg:h-9 lg:w-9",
  },
  {
    id: "gnome",
    name: "GNOME",
    category: "Business, Automation & Commerce",
    imageSrc: "/assets/tech-stack/gnome.svg",
    imageClassName: "h-8 w-8 object-contain lg:h-9 lg:w-9",
  },
  {
    id: "notion",
    name: "Notion",
    category: "Business, Automation & Commerce",
    icon: SiNotion,
    color: "#FFFFFF",
  },
  {
    id: "figma",
    name: "Figma",
    category: "Design & Creative",
    imageSrc: "/assets/tech-stack/figma.svg",
    imageClassName: "h-9 w-7 object-contain lg:h-10 lg:w-8",
  },
  {
    id: "adobe",
    name: "Adobe",
    category: "Design & Creative",
    imageSrc: "/assets/tech-stack/adobe.svg",
    imageClassName: "h-8 w-9 object-contain lg:h-9 lg:w-10",
  },
];

export const techStackRowOne = techStackItems.filter((_, index) => index % 2 === 0);
export const techStackRowTwo = techStackItems.filter((_, index) => index % 2 !== 0);
